### ISSUE TITLE
Docs Navigation Issue

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#429]
### What version are you using?

I think this is especially confusing with the how-to guides that have sub sections that are reflected in the breadcrumbs but not the sidebar, 

![image](https://github.com/stellar/stellar-docs/assets/734336/ee23388a-f900-4503-ad9f-cc9603d3af49)

![image](https://github.com/stellar/stellar-docs/assets/734336/bcc00ce1-f976-46f9-b854-c7df2ecd71e1)

Additionally: Some further issues with navigation. The categories listed in How-To guides are not clickable, though you can navigate to these pages through breadcrumbs and search, but these can be pretty barren. See example of the State Expiration how-to guides category page https://developers.stellar.org/docs/smart-contracts/guides/archival

**Comment by briwylde08** [comment]
I think it could make sense to make the main categories clickable to follow the breadcrumbs but I would argue that putting all the How-To Guides in the sidebar would be super messy. Especially since we're aiming to create way more How-To Guides in the future. I don't know if putting the How-To Guides in the sidebar is worth how chaotic it will look! I would find it overwhelming coming into the docs.

**Comment by briwylde08** [comment]
Maybe we can fold into docs merge v2
