### ISSUE TITLE
CLI docs should describe where the config files are and how to overwrite

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#815]
### What problem does your feature solve?
It appears that some developers are unaware of where to find and use the config files

### What would you like to see?
A page about the CLI describing the config files and how can ovewrite

**Comment by leighmcculloch** [comment]
To a large degree the config files are an implementation detail of the cli. 

If their contents become documented they become an api. 

There's benefits to discussing they exist but unclear to me if there's benefits right now to discussing their internals.

**Comment by janewang** [comment]
Hmm, I see.  I think there are use cases where users may want to overwrite the content to associate a keypair of their choosing

**Comment by willemneal** [comment]
I think it's worth mentioning where you can find the files. But I agree that we might want to change the config data representation in the future and could migrate users data for them and their code will break if they had ways of trying to look up info by reading the files directly. Projects Loam, however, will have to use them because we don't want to pull in the CLI crate to access the data. But for use we are very aware of the changes and will also hide the details from end users.

**Comment by leighmcculloch** [comment]
> I think there are use cases where users may want to overwrite the content to associate a seedphrase derived from keypair of their choosing

I think that's something we could add a command for if it's a workflow that needs supporting.

Devs will also naturally dig into config files and fiddle with them as they need to, without us promoting that it is a stable API, so not documenting it is not prohibiting someone doing that with the config file if they need.

**Comment by janewang** [comment]
Hmm okay, I could close this but I think it's worth mentioning where the config files are.
